### PR TITLE
Fixed off by one error in OnCreateViewHolder method

### PR DESCRIPTION
**Pull request by TJBlack31**
Hello, 

I created a hasHeader boolean class variable to adjust the adapter position accordingly.

It seems to work correctly now.

Thank you for reviewing!

-TJBlack31

changes

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
@TJBlack31 Thanks, this looks good. Can you change the target SDK back to 27?

**Comment by TJBlack31** [comment]
@Jawnnypoo Ok, I think we are good to go now. Thank you :)

Edit: I meant for the commit to say "SDK" not "API".  My bad

**Comment by TJBlack31** [comment]
@Jawnnypoo, are these changes now up to par?

Thank you
-TJB

**Comment by Jawnnypoo** [comment]
Yep, looks great! Thanks!

**Pull request merged**
